### ISSUE TITLE
'division by zero' error in pure pursuit controller

### ISSUE THREAD

**Issue by ysli16** [idsc-frazzoli/dg-commons#119]
A protection against the 'division by zero' error could be desirable in [this](https://github.com/idsc-frazzoli/dg-commons/blob/1bf45a4df80e02f315993b8e03f738899cd091f9/src/dg_commons/controllers/pure_pursuit.py#L103_compute_ddelta) line and the line below. 
Such an error occurs when the initial heading and the goal heading are identical(likely to happen when testing with customized commonroad scenarios).

**Comment by alezana** [comment]
@ysli16 thx, feel free to open a PR
