### ISSUE TITLE
Animation problem: player name is not moving properly

### ISSUE THREAD

**Issue by TracyLeee** [idsc-frazzoli/dg-commons#61]
In the animation, the name of the player does not move in accordance with the vehicle's occupancy. The name just stays still. For example:
![220929151509](https://user-images.githubusercontent.com/71379013/207594991-5f04ba23-6d70-4793-93f6-559e03fba9e7.gif)

**Comment by alezana** [comment]
@TracyLeee please provide a more detailed description

**Comment by TracyLeee** [comment]
Updated.

**Comment by alezana** [comment]
fixed
